sims_directory: '../extract_sehgal/manusmaps/flat_maps_large/latestmaps13092020/'
savingdirectory: ''
#ells, ctt, ctt_lensed, detectnoise, fftot, fg, ftSZ
spectra_path: '../extract_sehgal/LensQuEst-1/spectra_lensqest_un_len_detectnoise_fftot_fg_ftSZ.txt'

Lmin: 20
Lmax: 6000

logmode: True
nlogBins: 20
deltalplot: 50


Nsims: 80

fgnamefiles: ['tsz']


estimators:

        bh:
                nu: 148
                hardening: src
